name: Go

on: 
  push:
    tags:
    - '*'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -v -installsuffix cgo -ldflags "-w -s -extldflags '-static' " ./...

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Get current tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    
    - name: Create release
      run: tar -czvf release-${{steps.tag.outputs.tag}}.tar.gz front-entry.service front-entry config.toml
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release-${{steps.tag.outputs.tag}}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
